CREATE TABLE Item
(
	id			INT	IDENTITY(120160, 1)		PRIMARY KEY,
	itemName	VARCHAR(64)		NOT NULL	UNIQUE,
	itemDesc	VARCHAR(128)	NOT NULL,
	unitPrice	DECIMAL(10, 4)	NOT NULL,
	itemStatus	VARCHAR(2)		NOT NULL,
	CONSTRAINT	UPRICE_LIM CHECK (unitPrice >= 0),
	CONSTRAINT	VALUES_ITEMSTAT	CHECK (itemStatus IN ('AV', 'NA'))
);

CREATE TABLE Client
(
	id				INT	IDENTITY(220160, 1)	PRIMARY KEY,
	clientName		VARCHAR(64)		UNIQUE	NOT NULL,
	clientAddress	VARCHAR(32)		NOT NULL,
	clientStatus	VARCHAR(2)		NOT NULL,
	CONSTRAINT VALUES_CLIENTSTAT CHECK (clientStatus IN ('AC', 'IN'))
);

CREATE TABLE Warehouse
(
	id				INT	IDENTITY(320160, 1)			PRIMARY KEY,
	warehouseName	VARCHAR(64)		UNIQUE			NOT NULL,
	warehouseDesc	VARCHAR(128)	NOT NULL,
	warehouseStatus	VARCHAR(2)		NOT NULL,
	CONSTRAINT	VALUES_WAREHOUSESTAT	CHECK (warehouseStatus in ('OP', 'CL'))
);
